### ISSUE TITLE
Никак не могу включить русский язык на 4.0.4

### ISSUE THREAD

**Issue by amishakov** [stayen/sendy-translations#1]
Взял ваш перевод, но при переключении ничего не происходит.

**Comment by stayen** [comment]
Убедитесь, что файлы перевода default.mo, default.po расположены в каталоге
locale/ru_RU/LC_MESSAGES
установки Sendy, и доступны под UID, под которым работает Web сервер

После этого в настройках бренда ("Settings"  в правом верхнем пункте) пролистайте до "Select your language" - в выпадающем меню должен быть пункт "ru_RU". Выберите его и сохраните настройки.

Проверил - работает на 4.0.4.1.

Дополнительно: попробуйте "выйти и войти", если не все строки перевода задействованы.
