### ISSUE TITLE
[feature] Исходная папка со строками

### ISSUE THREAD

**Issue by akolnoochenko** [stayen/sendy-translations#2]
Добрый день!

Можно ли включить в репозиторий en_EN папку? Чтобы видеть разницу между релизом, для которого сделан перевод и текущим. 
У меня сейчас 4.0.7 на сервере – думал взять перевод, но боюсь на какой-нибудь странице gettext не найдёт сообщение и PHP упадёт на этом. А так бы можно было бы сделаьб diff исходного en_EN с тем что на бою и добавить нужные строки в перевод.

**Comment by stayen** [comment]
Сделано.

NB: если нет нужного перевода, PHP просто отобразит строку на английском языке.
